from __future__ import annotations

from numpy.typing import ArrayLike

def stirling_mutual_information(contingency_table: ArrayLike) -> float: ...
def traditional_mutual_information(contingency_table: ArrayLike) -> float: ...
def adjusted_mutual_information(contingency_table: ArrayLike) -> float: ...
def reduced_flat_mutual_information(contingency_table: ArrayLike) -> float: ...
def reduced_mutual_information(contingency_table: ArrayLike) -> float: ...
def H_ng_G_alpha(ng: ArrayLike, alpha: float) -> float: ...
def H_ngc_G_nc_alpha(ngc: ArrayLike, alpha: float) -> float: ...
